smatch: fix few warnings
NORETURN needs to be used on header and source file:

    error: symbol 'err_sys' redeclared with different type (originally
    declared at utils.h:58) - different modifiers

And function attribute ought to be positioned before declaration:

    utils.c:75:1: error: attributes should be specified before the
    declarator in a function definition

Secondly whole bunch of static key words in front of front of symbols needed.

    warning: symbol 'ripe_servers' was not declared. Should it be static?

Finally return NULL instead of zero when nothing is found in is_new_gtld().

    warning: Using plain integer as NULL pointer